name: getting_started_with_nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - spacy=3.1.3
  - gensim=3.8
  - matplotlib=3.1.3
  - scikit-learn=0.22
  - numpy=1.18
  - pandas=1.0
  - notebook
prefix: /home/hbunyamin/miniconda3/envs/getting_started_with_nlp
